# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Métricas Boss - Agência de Web Analytics!
email: contato@metricasboss.com.br
description: A Métricas Boss é uma agência de Web Analytics e usabilidade. Conte com uma empresa certificada Google Analytics para sua gestão de web analytics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://metricasboss.com.br" # the base hostname & protocol for your site

permalink: /:title.html
exclude: ['node_modules', 'Gulpfile.js', 'package.json', 'README.md', 'Gemfile', 'Gemfile.lock', 'config.rb']
# Build settings
markdown: kramdown
gems:
- jekyll-compass
